# General Jekyll Config
highlighter: pygments
url: https://erdinckaya.org
lsi: false
paginate: 10
paginate_path: "/blog/page:num/"
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
