# General Jekyll Config
highlighter: rouge
url: https://erdinckaya.org
lsi: false
paginate: 20
paginate_path: "/blog/page:num/"
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
